### ISSUE TITLE
`GraphQL-ESLint` v4 Roadmap

### ISSUE THREAD

**Issue by B2o5T** [B2o5T/graphql-eslint#981]
- [x] Node 12/14/16 drop support https://github.com/B2o5T/graphql-eslint/pull/1793
- [x] Support <s>ESLint 9</s>, drop support for ESLint 7 <s>and 8</s> (require at least 8.44) https://github.com/B2o5T/graphql-eslint/pull/1812
- [x] Support GraphQL 17 https://github.com/B2o5T/graphql-eslint/pull/1793
- [x] <s>Bundle to ESM only</s>
- [x] <s>rename `parserOptions.operations` to `parserOptions.documents` to make consistency with `graphql-config` </s> https://github.com/B2o5T/graphql-eslint/issues/770#issuecomment-967561242 https://github.com/B2o5T/graphql-eslint/issues/1087
> Was used a different approach https://github.com/B2o5T/graphql-eslint/pull/1795
- [x] Remove `GraphQLRuleTester` from bundle <s>and publish as `@graphql-eslint/rule-tester`</s> https://github.com/B2o5T/graphql-eslint/issues/946#issuecomment-1030802927 https://github.com/B2o5T/graphql-eslint/pull/1792
- [x] `alphabetize` changes
  - add `definitions: true` option for `all` config
  - rename `values: ['EnumTypeDefinition']` to `values: true`, <s>add `variables: ['OperationDefinition', 'FragmentDefinition']`</s> https://github.com/B2o5T/graphql-eslint/pull/1812
- [x] bring back `possible-type-extension` to `recommended` config https://github.com/B2o5T/graphql-eslint/pull/1794
- [x] Remove `unique-enum-value-names` rule, <s>rename `no-case-insensitive-enum-values-duplicates` to  `unique-enum-value-names` with new option `caseSensitive`</s> https://github.com/B2o5T/graphql-eslint/discussions/793 https://github.com/B2o5T/graphql-eslint/pull/1812
- [x] Add `unique-operation-name` and `unique-fragment-name` rules to `recommended` config. https://github.com/B2o5T/graphql-eslint/pull/1794
> The whole concept of sibling operations provided by `parserOptions.operations` or `graphql-config`'s `documents` fields is based on uniquely named operations and fragments, for omitting false-positive/negative cases when operations and fragments are located in separated files. For this reason, these rules must be included in `recommended` config

- [x] enable `strict: true` in `tsconfig.json` https://github.com/B2o5T/graphql-eslint/pull/1352
- [ ] `known-directives` remove `ignoreClientDirectives` in favour of graphql-config's `extensions.customDirectives` https://github.com/B2o5T/graphql-eslint/issues/1076#issuecomment-1143594491
- [x] rename `require-id-when-available` to `require-selections` https://github.com/B2o5T/graphql-eslint/issues/1159 https://github.com/B2o5T/graphql-eslint/pull/1812
- [x] <s>remove requiring description for fields and</s> add `rootField: true` to `schema-recommended` config https://github.com/B2o5T/graphql-eslint/pull/1812
- [x] rename `relay` config to `schema-relay` https://github.com/B2o5T/graphql-eslint/pull/1794
- [x] <s>add `spaced-comment` to recommended config</s> (has bugs with graphql language https://github.com/eslint/eslint/issues/17145)

**Comment by vihangm** [comment]
Hey @dimaMachina are there any plans to publish a v4 release on npm?

**Comment by osdiab** [comment]
I also ask since the current version of graphql-eslint actually is causing vulnerability alerts for `ws` due to an old version of `graphql-config`. anything blocking the current alpha from being stable?

**Comment by dimaMachina** [comment]
[GraphQL ESLint v4 was released](https://github.com/dimaMachina/graphql-eslint/releases/tag/release-1732628569973) so closing it
